KSystem.Nop.Plugin.Misc.AutoTesting/Models/TestingPages/TestingCommandGridModel.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
{
    using global::Nop.Web.Framework.Models;

    public record TestingCommandGridModel : BasePagedListModel<TestingCommandModel>
    {
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Models/TestingPages/TestingCommandModel.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
{
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc.Rendering;

    using global::Nop.Web.Framework.Models;
    using global::Nop.Web.Framework.Mvc.ModelBinding;

    public record TestingCommandModel : BaseNopEntityModel
    {
        public TestingCommandModel()
        {
            AvailableCommandTypes = new List<SelectListItem>();
        }

        public int PageId { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.CommandType")]
        public int CommandTypeId { get; set; }
        public string CommandTypeName { get; set; }
        public IList<SelectListItem> AvailableCommandTypes { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Selector")]
        public string Selector { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Value")]
        public string Value { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Name")]
        public string Name { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Message")]
        public string Message { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.CommandOrder")]
        public int CommandOrder { get; set; }
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Models/TestingPages/TestingCommandSearchModel.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
{
    using global::Nop.Web.Framework.Models;

    public record TestingCommandSearchModel : BaseSearchModel
    {
        public int TestingPageId { get; set; }
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Models/TestingPages/TestingPageGridModel.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
{
    using global::Nop.Web.Framework.Models;

    public record TestingPageGridModel : BasePagedListModel<TestingPageModel>
    {       
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Models/TestingPages/TestingPageModel.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
{
    using System.ComponentModel.DataAnnotations;

    using global::Nop.Web.Framework.Models;
    using global::Nop.Web.Framework.Mvc.ModelBinding;

    public record TestingPageModel : BaseNopEntityModel
    {
        public TestingPageModel()
        {
            CommandSearchModel = new TestingCommandSearchModel();
            CommandSearchModel.SetGridPageSize();
        }

        [NopResourceDisplayName("Admin.System.SeNames.Name")]
        [Required]
        public string Name { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.TestingUrl")]
        public string TestingUrl { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.CustomUrlProvider")]
        public string CustomUrlProvider { get; set; }

        [NopResourceDisplayName("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.ProviderParametersWithFormat")]
        public string ProviderParameters { get; set; }

        public TestingCommandSearchModel CommandSearchModel { get; set; }

        public bool IsModelCreate { get; set; }
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Models/TestingPages/TestingPageSearchModel.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
{
    using global::Nop.Web.Framework.Models;

    public record TestingPageSearchModel : BaseSearchModel
    {       
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Controllers/TestingPagesController.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;

    using KSystem.Nop.Plugin.Misc.AutoTesting.Domain;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Services;

    using global::Nop.Services.Localization;
    using global::Nop.Services.Messages;
    using global::Nop.Services.Security;
    using global::Nop.Web.Areas.Admin.Controllers;
    using global::Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
    using global::Nop.Web.Framework;
    using global::Nop.Web.Framework.Controllers;
    using global::Nop.Web.Framework.Models.Extensions;
    using global::Nop.Web.Framework.Mvc;
    using global::Nop.Web.Framework.Mvc.Filters;

    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public partial class TestingPagesController : BaseAdminController
    {
        private readonly ILocalizationService _localizationService;

        private readonly INotificationService _notificationService;

        private readonly IPermissionService _permissionService;

        private readonly ITestingPageService _testingPageService;

        public TestingPagesController(
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ITestingPageService testingPageService)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _testingPageService = testingPageService;
        }

        public virtual async Task<IActionResult> List()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var model = new TestingPageSearchModel();

            model.SetGridPageSize();

            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> GridList(TestingPageSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return await AccessDeniedDataTablesJson();
            }

            var records = await _testingPageService.GetAllTestingPagesAsync(searchModel.Page - 1, searchModel.PageSize);

            var model = new TestingPageGridModel().PrepareToGrid(searchModel, records, () =>
            {
                return records.Select(x =>
                {
                    return x.ToModel<TestingPageModel>();
                });
            });

            return Json(model);
        }

        public virtual async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var model = new TestingPageModel
            {
                IsModelCreate = true
            };

            return View(model);
        }

        [HttpPost]
        [ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual async Task<IActionResult> Create(TestingPageModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            if (ModelState.IsValid)
            {
                var testingPage = model.ToEntity<TestingPage>();
                await _testingPageService.SaveTestingPageEntryAsync(testingPage);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("KSystem.Nop.Plugin.Core.Views.AddSuccess"));
                return continueEditing
                           ? RedirectToAction("Edit", new { id = testingPage.Id })
                           : RedirectToAction("List");
            }

            model.IsModelCreate = true;

            return View(model);
        }

        public virtual async Task<IActionResult> Edit(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var testingPage = await _testingPageService.GetTestingPageByIdAsync(id);
            if (testingPage == null)
            {
                return RedirectToAction("List");
            }

            var model = testingPage.ToModel<TestingPageModel>();
            model.CommandSearchModel.TestingPageId = id;

            return View(model);
        }

        [HttpPost]
        [ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual async Task<IActionResult> Edit(TestingPageModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var testingPage = await _testingPageService.GetTestingPageByIdAsync(model.Id);

            if (ModelState.IsValid)
            {
                testingPage = model.ToEntity(testingPage);
                await _testingPageService.SaveTestingPageEntryAsync(testingPage);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("KSystem.Nop.Plugin.Core.Views.UpdateSuccess"));

                if (continueEditing)
                {
                    SaveSelectedTabName();

                    return RedirectToAction("Edit", new { id = testingPage.Id });
                }

                return RedirectToAction("List");
            }

            model.CommandSearchModel.TestingPageId = testingPage.Id;

            return View(model);
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("copy-test-page")]
        public virtual async Task<IActionResult> CopyTestingPage(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var testingPage = await _testingPageService.GetTestingPageByIdAsync(id);
            var testingCommands = await _testingPageService.GetAllTestingCommandsByPageIdAsync(id);

            testingPage.Id = default(int);
            testingPage.Name += " - Copy";

            await _testingPageService.SaveTestingPageEntryAsync(testingPage);

            foreach (var testingCommand in testingCommands)
            {
                testingCommand.Id = default(int);
                testingCommand.PageId = testingPage.Id;

                await _testingPageService.SaveTestingCommandEntryAsync(testingCommand);
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public virtual async Task<IActionResult> Delete(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            await _testingPageService.DeleteTestingPageEntryAsync(id);

            return RedirectToAction("List");
        }

        [HttpPost]
        public virtual async Task<IActionResult> DeleteTestingPage(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return await AccessDeniedDataTablesJson();
            }

            await _testingPageService.DeleteTestingPageEntryAsync(id);

            return new NullJsonResult();
        }
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingPages/Create.cshtml
@using Nop.Web.Framework.UI
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages.TestingPageModel

@{
    Layout = "_AdminLayout";

    NopHtml.SetActiveMenuItemSystemName("KSystem.AutoTesting.TestingPages");
}

<form asp-controller="TestingPages" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("KSystem.Nop.Plugin.Misc.AutoTesting.TestingPages") - @T("Admin.Common.AddNewRecord")
            <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("KSystem.Nop.Plugin.Misc.AutoTesting.BackToList").Text, "List")</small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingPages/Edit.cshtml
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages.TestingPageModel

@{
    Layout = "_AdminLayout";

    NopHtml.SetActiveMenuItemSystemName("KSystem.AutoTesting.TestingPages");
}

<form asp-controller="TestingPages" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("KSystem.Nop.Plugin.Misc.AutoTesting.TestingPages") -
            @if (Model.Id > default(int))
            {
                @Model.Name 
            }
            else
            {
                @T("Admin.Common.AddNewRecord")
            }
            <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("KSystem.Nop.Plugin.Misc.AutoTesting.BackToList").Text, "List")</small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <button type="submit" class="btn btn-success" id="copy-test-page" name="copy-test-page">
                <i class="far fa-copy"></i>
                @T("KSystem.Nop.Plugin.Misc.AutoTesting.Copy")
            </button>
            <span id="testingpages-delete" class="btn bg-red">
                <i class="fas fa-trash"></i>
                @T("Admin.Common.Delete")
            </span>
            <nop-action-confirmation asp-model-id="@Model.Id" asp-button-id="copy-test-page" asp-additional-confirm="KSystem.Nop.Plugin.Core.CopyItemMessage" />
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="testingpages-delete" />

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingPages/List.cshtml
@using KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
@model TestingPageSearchModel

@{
    NopHtml.SetActiveMenuItemSystemName("KSystem.AutoTesting.TestingPages");
}

@{
    Layout = "_AdminLayout";
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("KSystem.Nop.Plugin.Misc.AutoTesting.TestingPages")
    </h1>
    <div class="float-right">
        <a asp-action="Create" class="btn btn-primary">
            <i class="fa fa-plus-square"></i>
            @T("Admin.Common.AddNew")
        </a>
    </div>
</div>

<section class="content">
    <div class="card-group">
        <div class="card card-default">
            <div class="card-body">
                @await Html.PartialAsync("Table", new DataTablesModel
                {
                   Name = "testing-pages-grid",
                   UrlRead = new DataUrl("GridList", "TestingPages", null),
                   UrlDelete = new DataUrl("DeleteTestingPage", "TestingPages", null),
                   Length = Model.PageSize,
                   LengthMenu = Model.AvailablePageSizes,
                   ColumnCollection = new List<ColumnProperty>
                        {
                        new ColumnProperty(nameof(TestingPageModel.Name))
                        {
                            Title = T("Admin.System.SeNames.Name").Text
                        },
                        new ColumnProperty(nameof(TestingPageModel.TestingUrl))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.TestingUrl").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingPageModel.CustomUrlProvider))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.CustomUrlProvider").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingPageModel.ProviderParameters))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.ProviderParameters").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingPageModel.Id))
                        {
                            Title = T("Admin.Common.Edit").Text,
                            Width = "150",
                            ClassName =  NopColumnClassDefaults.Button,
                            Render = new RenderButtonEdit(new DataUrl("Edit"))
                        },
                        new ColumnProperty(nameof(TestingPageModel.Id))
                        {
                            Title = T("Admin.Common.Delete").Text,
                            Width = "150",
                            ClassName =  NopColumnClassDefaults.Button,
                            Render = new RenderButtonRemove(T("Admin.Common.Delete").Text)
                        }
                    }
                })
            </div>
        </div>
    </div>
</section>

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingPages/_CreateOrUpdate.Commands.cshtml
@using KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages
@model TestingCommandSearchModel

<section class="content">
    <div class="card-group">
        <div class="card card-default">
            <div class="card-body">
                @await Html.PartialAsync("Table", new DataTablesModel
                {
                   Name = "testing-commands-grid",
                   UrlRead = new DataUrl("GridList", "TestingCommands",
                        new RouteValueDictionary(new { testingPageId = Model.TestingPageId })),
                   UrlDelete = new DataUrl("Delete", "TestingCommands", null),
                   Length = Model.PageSize,
                   LengthMenu = Model.AvailablePageSizes,
                   ColumnCollection = new List<ColumnProperty>
                        {
                        new ColumnProperty(nameof(TestingCommandModel.CommandTypeId))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.CommandType").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll,
                            Render = new RenderCustom("getCommandName")
                        },
                        new ColumnProperty(nameof(TestingCommandModel.Selector))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Selector").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingCommandModel.Name))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Name").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingCommandModel.Value))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Value").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingCommandModel.Message))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.Message").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingCommandModel.CommandOrder))
                        {
                            Title = T("KSystem.Nop.Plugin.Misc.AutoTesting.Fields.CommandOrder").Text,
                            ClassName =  NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(TestingCommandModel.Id))
                        {
                            Title = T("Admin.Common.Edit").Text,
                            Width = "150",
                            ClassName =  NopColumnClassDefaults.Button,
                            Render = new RenderCustom("renderEditButton")
                        },
                        new ColumnProperty(nameof(TestingCommandModel.Id))
                        {
                            Title = T("Admin.Common.Delete").Text,
                            Width = "150",
                            ClassName =  NopColumnClassDefaults.Button,
                            Render = new RenderButtonRemove(T("Admin.Common.Delete").Text)
                        }
                    }
                })
            </div>
            <div class="card-footer">
                <a class="btn btn-primary"
                   href="javascript:OpenWindow('@Url.Action("CreateOrUpdate", "TestingCommands")?testingPageId=@Model.TestingPageId&amp;btnId=refreshCommandsList&amp;', 800, 500, true);">
                    <i class="fas fa-plus-square"></i>
                    @T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.AddNewCommand")
                </a>
            </div>
            <div>
                <button type="submit" id="refreshCommandsList" style="display: none;"></button>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('#refreshCommandsList').click(function () {
                            updateTable('#testing-commands-grid');
                            return false;
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    function getCommandName(data, type, row, meta) {
        return row.CommandTypeName;
    }

    function renderEditButton(data, type, row, meta) {
        return '<button class="btn btn-default" onclick="OpenWindow(\'@Url.Action("CreateOrUpdate", "TestingCommands")/'
            + row.Id + '?testingPageId=@Model.TestingPageId&btnId=refreshCommandsList\', 800, 500, true);return false;" title="@T("Admin.Common.Edit")">'
            + '<i class="fas fa-pencil-alt"></i>'
            + '@T("Admin.Common.Edit")'
            + '</button>';
    }
</script>

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingPages/_CreateOrUpdate.Common.cshtml
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages.TestingPageModel

<div class="card-body">
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="Name" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="TestingUrl" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="TestingUrl" />
            <span asp-validation-for="TestingUrl"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="CustomUrlProvider" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="CustomUrlProvider" />
            <span asp-validation-for="CustomUrlProvider"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="ProviderParameters" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="ProviderParameters" />
            <span asp-validation-for="ProviderParameters"></span>
        </div>
    </div>
</div>

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingPages/_CreateOrUpdate.cshtml
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages.TestingPageModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <nop-tabs id="testing-pages-edit">
                <nop-tab asp-name="tab-common" asp-title="@T("Admin.Configuration.Settings.GeneralCommon")" asp-default="true">
                    @await Html.PartialAsync("_CreateOrUpdate.Common", Model)
                </nop-tab>

                @if (!Model.IsModelCreate)
                {
                    <nop-tab asp-name="tab-list-of-commands" asp-title="@T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.TestingCommands")">
                        @await Html.PartialAsync("_CreateOrUpdate.Commands", Model.CommandSearchModel)
                    </nop-tab>
                }
            </nop-tabs>
        </div>
    </div>
</section>