KSystem.Nop.Plugin.Misc.AutoTesting/Controllers/TestingCommandsController.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;

    using KSystem.Nop.Plugin.Misc.AutoTesting.Domain;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Enums;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Extensions;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Services;

    using global::Nop.Services.Localization;
    using global::Nop.Services.Messages;
    using global::Nop.Services.Security;
    using global::Nop.Web.Areas.Admin.Controllers;
    using global::Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
    using global::Nop.Web.Framework;
    using global::Nop.Web.Framework.Models.Extensions;
    using global::Nop.Web.Framework.Mvc;
    using global::Nop.Web.Framework.Mvc.Filters;

    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public partial class TestingCommandsController : BaseAdminController
    {
        private readonly ILocalizationService _localizationService;

        private readonly INotificationService _notificationService;

        private readonly IPermissionService _permissionService;

        private readonly ITestingPageService _testingPageService;

        public TestingCommandsController(
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ITestingPageService testingPageService)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _testingPageService = testingPageService;
        }

        [HttpPost]
        public virtual async Task<IActionResult> GridList(TestingCommandSearchModel searchModel, int testingPageId)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return await AccessDeniedDataTablesJson();
            }

            var records = await _testingPageService.GetAllTestingCommandsByPageIdAsync(
                testingPageId, searchModel.Page - 1, searchModel.PageSize);
            var allCommandTypes = CommandType.AjaxComplete.ToSelectList();

            var model = new TestingCommandGridModel().PrepareToGrid(searchModel, records, () =>
            {
                return records.Select(x =>
                {
                    var result = x.ToModel<TestingCommandModel>();

                    result.CommandTypeName = allCommandTypes.FirstOrDefault(y => y.Value == x.CommandTypeId.ToString())?.Text;

                    return result;
                });
            });

            return Json(model);
        }

        public virtual async Task<IActionResult> CreateOrUpdate(int id, int testingPageId)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var model = new TestingCommandModel
            {
                PageId = testingPageId
            };

            if (id > default(int))
            {
                var testingCommand = await _testingPageService.GetTestingCommandByIdAsync(id);

                if (testingCommand != null)
                {
                    model = testingCommand.ToModel<TestingCommandModel>();
                }
            }

            model.AvailableCommandTypes = CommandType.AjaxComplete.ToSelectList();

            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> CreateOrUpdate(TestingCommandModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            if (ModelState.IsValid)
            {
                ViewBag.RefreshPage = true;

                var entity = model.ToEntity<TestingCommand>();

                await _testingPageService.SaveTestingCommandEntryAsync(entity);

                return View(model);
            }

            model.AvailableCommandTypes = CommandType.AjaxComplete.ToSelectList();

            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> Delete(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            await _testingPageService.DeleteTestingCommandEntryAsync(id);

            return new NullJsonResult();
        }
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingCommands/CreateOrUpdate.cshtml
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingPages.TestingCommandModel

@{
    Layout = "_AdminPopupLayout";

    if (Model.Id > default(int))
    {
        ViewBag.PageTitle = T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.UpdateCommand").Text;
    }
    else
    {
        ViewBag.PageTitle = T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.AddNewCommand").Text;
    }
}

<form asp-controller="TestingCommands" asp-action="CreateOrUpdate" asp-route-btnId="@Context.Request.Query["btnId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @if (Model.Id > default(int))
            {
                @T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.UpdateCommand")
            }
            else
            {
                @T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.AddNewCommand")
            }
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <div asp-validation-summary="All"></div>
    <input asp-for="PageId" type="hidden" />

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="cards-group">
                    <div class="card card-default card-popup">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="CommandTypeId" />
                                </div>
                                <div class="col-md-9">
                                    <nop-select asp-for="CommandTypeId" asp-items="Model.AvailableCommandTypes" />
                                    <span asp-validation-for="CommandTypeId"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="Selector" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="Selector" />
                                    <span asp-validation-for="Selector"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="Value" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="Value" />
                                    <span asp-validation-for="Value"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="Name" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="Name" />
                                    <span asp-validation-for="Name"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="Message" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="Message" />
                                    <span asp-validation-for="Message"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="CommandOrder" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="CommandOrder" />
                                    <span asp-validation-for="CommandOrder"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @if (ViewBag.RefreshPage == true)
    {
        <script type="text/javascript">
            var refreshButton = window.opener.document.getElementById('@(Context.Request.Query["btnId"])');

            if (typeof (refreshButton) != 'undefined' && refreshButton != null) {
                refreshButton.click();
            }

            window.close();
        </script>
    }
</form>