KSystem.Nop.Plugin.Misc.AutoTesting/Controllers/TestingTaskPagesController.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;

    using KSystem.Nop.Plugin.Misc.AutoTesting.Domain;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingTasks;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Services;

    using global::Nop.Services.Security;
    using global::Nop.Web.Areas.Admin.Controllers;
    using global::Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
    using global::Nop.Web.Framework;
    using global::Nop.Web.Framework.Models.Extensions;
    using global::Nop.Web.Framework.Mvc;
    using global::Nop.Web.Framework.Mvc.Filters;

    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public partial class TestingTaskPagesController : BaseAdminController
    {
        private readonly IPermissionService _permissionService;

        private readonly ITestingPageService _testingPageService;

        private readonly ITestingTaskService _testingTaskService;

        public TestingTaskPagesController(
            IPermissionService permissionService,
            ITestingPageService testingPageService,
            ITestingTaskService testingTaskService)
        {
            _permissionService = permissionService;
            _testingPageService = testingPageService;
            _testingTaskService = testingTaskService;
        }

        [HttpPost]
        public virtual async Task<IActionResult> GridList(TestingTaskPageSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return await AccessDeniedDataTablesJson();
            }

            var records = await _testingTaskService.GetAllTestingPagesByTaskIdAsync(
                searchModel.TestingTaskId, searchModel.Page - 1, searchModel.PageSize);
            var allTestingPages = await _testingPageService.GetAllTestingPagesAsync();

            var model = new TestingTaskPageGridModel().PrepareToGrid(searchModel, records, () =>
            {
                return records.Select(x =>
                {
                    var result = x.ToModel<TestingTaskPageModel>();

                    result.PageName = allTestingPages.FirstOrDefault(y => y.Id == x.PageId)?.Name;

                    return result;
                });
            });

            return Json(model);
        }

        public virtual async Task<IActionResult> AddOrUpdate(int id, int testingTaskId)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var model = new TestingTaskPageModel
            {
                TaskId = testingTaskId
            };

            if (id > default(int))
            {
                var testingTaskPage = await _testingTaskService.GetTestingTaskPageMapByIdAsync(id);

                if (testingTaskPage != null)
                {
                    model = testingTaskPage.ToModel<TestingTaskPageModel>();
                }
            }

            model.AvailablePages = await GetPagesSelectListAsync();

            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> AddOrUpdate(TestingTaskPageModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            if (ModelState.IsValid)
            {
                ViewBag.RefreshPage = true;

                var entity = model.ToEntity<TestingTaskPageMap>();

                await _testingTaskService.SaveTestingTaskPageMapEntryAsync(entity);

                return View(model);
            }

            model.AvailablePages = await GetPagesSelectListAsync();

            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> Delete(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            await _testingTaskService.DeleteTestingTaskPageMapEntryAsync(id);

            return new NullJsonResult();
        }

        private async Task<IList<SelectListItem>> GetPagesSelectListAsync()
        {
            return await (await _testingPageService.GetAllTestingPagesAsync()).Select(x =>
                new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToListAsync();
        }
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Views/TestingTaskPages/AddOrUpdate.cshtml
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.TestingTasks.TestingTaskPageModel

@{
    Layout = "_AdminPopupLayout";

    if (Model.Id > default(int))
    {
        ViewBag.PageTitle = T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.UpdateTaskPage").Text;
    }
    else
    {
        ViewBag.PageTitle = T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.AddExistingPage").Text;
    }
}

<form asp-controller="TestingTaskPages" asp-action="AddOrUpdate" asp-route-btnId="@Context.Request.Query["btnId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @if (Model.Id > default(int))
            {
                @T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.UpdateTaskPage")
            }
            else
            {
                @T("KSystem.Nop.Plugin.Misc.AutoTesting.Views.AddExistingPage")
            }
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <div asp-validation-summary="All"></div>
    <input asp-for="TaskId" type="hidden" />

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="cards-group">
                    <div class="card card-default card-popup">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="PageId" />
                                </div>
                                <div class="col-md-9">
                                    <nop-select asp-for="PageId" asp-items="Model.AvailablePages" />
                                    <span asp-validation-for="PageId"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="PageOrder" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="PageOrder" />
                                    <span asp-validation-for="PageOrder"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="IncludedInTask" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="IncludedInTask" />
                                    <span asp-validation-for="IncludedInTask"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @if (ViewBag.RefreshPage == true)
    {
        <script type="text/javascript">
            var refreshButton = window.opener.document.getElementById('@(Context.Request.Query["btnId"])');

            if (typeof (refreshButton) != 'undefined' && refreshButton != null) {
                refreshButton.click();
            }

            window.close();
        </script>
    }
</form>