KSystem.Nop.Plugin.Misc.AutoTesting/Controllers/AutoTestingPluginController.cs
namespace KSystem.Nop.Plugin.Misc.AutoTesting.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;

    using KSystem.Nop.Plugin.Misc.AutoTesting.Infrastructure;
    using KSystem.Nop.Plugin.Misc.AutoTesting.Models;

    using global::Nop.Services.Configuration;
    using global::Nop.Services.Localization;
    using global::Nop.Services.Messages;
    using global::Nop.Services.Security;
    using global::Nop.Web.Areas.Admin.Controllers;
    using global::Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
    using global::Nop.Web.Framework;
    using global::Nop.Web.Framework.Controllers;
    using global::Nop.Web.Framework.Mvc.Filters;

    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public partial class AutoTestingPluginController : BaseAdminController
    {
        private readonly ILocalizationService _localizationService;

        private readonly INotificationService _notificationService;

        private readonly IPermissionService _permissionService;

        private readonly ISettingService _settingService;

        private AutoTestingSettings _autoTestingSettings;

        public AutoTestingPluginController(
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            AutoTestingSettings autoTestingSettings)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _autoTestingSettings = autoTestingSettings;
        }

        public virtual async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            var model = _autoTestingSettings.ToSettingsModel<AutoTestingConfigureModel>();

            return View(model);
        }

        [HttpPost]
        [FormValueRequired("save", "save-continue")]
        public virtual async Task<IActionResult> Configure(AutoTestingConfigureModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
            {
                return AccessDeniedView();
            }

            _autoTestingSettings = model.ToSettings(_autoTestingSettings);

            await _settingService.SaveSettingAsync(_autoTestingSettings);
            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(
                await _localizationService.GetResourceAsync("KSystem.Nop.Plugin.Core.SuccessSaveNotification"));

            return await Configure();
        }
    }
}

KSystem.Nop.Plugin.Misc.AutoTesting/Views/AutoTestingPlugin/Configure.cshtml
@using Nop.Web.Framework.UI
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.AutoTestingConfigureModel

@{
    NopHtml.SetActiveMenuItemSystemName("KSystem.AutoTesting.Configuration");
}

@{
    Layout = "_AdminLayout";
}

<form asp-controller="AutoTestingPlugin" asp-action="Configure" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("KSystem.Nop.Plugin.Misc.AutoTesting.AutoTesting") - @T("Admin.Configuration.Settings")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <nop-cards id="auto-testing-plugin-cards">
                    <nop-card asp-name="configure-robot" asp-icon="fas fa-robot" asp-title="@T("KSystem.Nop.Plugin.Misc.AutoTesting.AutoTestingRobot")"
                              asp-hide-block-attribute-name="panel-robot" asp-hide="false" asp-advanced="false">@await Html.PartialAsync("_Configure.Robot", Model)
                    </nop-card>
                </nop-cards>
            </div>
        </div>
    </section>
</form>

KSystem.Nop.Plugin.Misc.AutoTesting/Views/AutoTestingPlugin/_Configure.Robot.cshtml
@model KSystem.Nop.Plugin.Misc.AutoTesting.Models.AutoTestingConfigureModel

<div class="card-body">
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="EnabledAutoTestingRobot" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="EnabledAutoTestingRobot" />
            <span asp-validation-for="EnabledAutoTestingRobot"></span>
        </div>
    </div>
</div>